### ISSUE TITLE
Tests need to work

### ISSUE THREAD

**Issue by erramuzpe** [compneurobilbao/bha#5]
Let's configure at least CircleCI, it's pretty easy, just follow the instructions. We also need new tests

**Comment by erramuzpe** [comment]
Tests running and passing in local, CircleCI not working due to conflicts.

**Comment by erramuzpe** [comment]
tests passed!

**Comment by erramuzpe** [comment]
@christiancarballo @uxuelazkano @emaudes I encourage you guys to take a look to the project. Atm, I've been able to make documentation, coverage and tests work. Just take a look and make any question you came up with. I will soon try to build a package in pypi. Agurtxo!

**Comment by erramuzpe** [comment]
look the super-cool badges in the projects README.md (first page) :rofl: 
click over them to go to the building, coveraging and documentation information.

**Comment by uxuelazkano** [comment]
All this means that the script we wrote worked properly?

**Comment by erramuzpe** [comment]
well, actually I had to make several changes :stuck_out_tongue: , but yep, overall it was quite correctly implemented. You could improve your PEP8 mistakes (spaces between function name and inputs, coma separations etc.). I also make some mistakes... take a look to the "issues" badge in README to have an idea.
