### ISSUE TITLE
Make automatic documentation work

### ISSUE THREAD

**Issue by erramuzpe** [compneurobilbao/bha#6]
Just follow readthedocs.org information and how to set up.

**Comment by erramuzpe** [comment]
works! http://bha.readthedocs.io/en/latest/

**Comment by emaudes** [comment]
Great! Finally, which was the issue we were having last week? How did you manage?

**Comment by erramuzpe** [comment]
It was a matter of the functions. Some of them were bad implemented, so I
deleted the ones that we were not going to use and worked :)

2017-03-08 20:06 GMT+01:00 emaudes <notifications@github.com>:

**Comment by emaudes** [comment]
Perfect! Good job!
